apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: network-bandwidth-example3
  namespace: chaos-paige
spec:
  action: bandwidth
  mode: one
  bandwidth:
    rate: 100kbps
    limit: 100
    buffer: 10000
    peakrate: 1000000
    minburst: 1000000
  duration: "10s"
  scheduler:
    cron: "@every 15s"