apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: etcd-network-delay
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - etcd
  delay:
    latency: "10ms"
    correlation: "100"
    jitter: "0ms"
  duration: "30s"
  scheduler:
    cron: "@every 60s"