apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: etcd-network-delay2
  namespace: chaos-testing
spec:
  action: delay
  mode: one
  delay:
    latency: "10ms"
    correlation: "100"
    jitter: "0ms"
  duration: "30s"
  scheduler:
    cron: "@every 60s"