#!/bin/bash
set -euo pipefail

# Called by the create-krkn-hub-pr workflow.
# Env vars required: GH_TOKEN, NEW_PLUGINS, GITHUB_WORKSPACE, COMMIT_SHA

SKELETON_DIR="${GITHUB_WORKSPACE}/.github/krkn-hub-skeleton"

git config --global user.email "github-actions[bot]@users.noreply.github.com"
git config --global user.name "github-actions[bot]"

git clone "https://x-access-token:${GH_TOKEN}@github.com/redhat-chaos/krkn-hub.git" /tmp/krkn-hub
cd /tmp/krkn-hub

for PLUGIN in $NEW_PLUGINS; do
  SCENARIO_NAME=$(echo "$PLUGIN" | tr '_' '-')
  BRANCH="add-scenario-${SCENARIO_NAME}"

  git checkout main
  git checkout -b "$BRANCH"

  mkdir -p "$SCENARIO_NAME"

  cp "$SKELETON_DIR/env.sh"             "$SCENARIO_NAME/env.sh"
  cp "$SKELETON_DIR/run.sh"             "$SCENARIO_NAME/run.sh"
  cp "$SKELETON_DIR/krknctl-input.json" "$SCENARIO_NAME/krknctl-input.json"

  # Substitute __SCENARIO__ placeholder in Dockerfile.template
  sed "s|__SCENARIO__|${SCENARIO_NAME}|g" \
    "$SKELETON_DIR/Dockerfile.template" > "$SCENARIO_NAME/Dockerfile.template"

  # Append new service block to docker-compose.yaml
  python3 - "$SCENARIO_NAME" << 'PYEOF'
import sys
name = sys.argv[1]
svc = (
    f"\n    {name}:\n"
    f"      build:\n"
    f"        context: ./\n"
    f"        dockerfile: ./{name}/Dockerfile\n"
    f"        platforms:\n"
    f"          - linux/amd64\n"
    f"          - linux/arm64\n"
    f"      image: quay.io/krkn-chaos/krkn-hub:{name}\n"
)
content = open("docker-compose.yaml").read()
open("docker-compose.yaml", "w").write(content.rstrip() + "\n" + svc)
PYEOF

  # Add new scenario to the SCENARIOS array in build.sh
  sed -i "s|)$| ${SCENARIO_NAME})|" build.sh

  git add "${SCENARIO_NAME}/" docker-compose.yaml build.sh
  git commit -m "chore: add skeleton for new scenario plugin ${SCENARIO_NAME}

Auto-generated by the create-krkn-hub-pr workflow in redhat-chaos/krkn.
Source plugin: krkn/scenario_plugins/${PLUGIN}"

  git push origin "$BRANCH"

  PR_BODY="## New scenario plugin detected

The plugin \`${PLUGIN}\` was added to [redhat-chaos/krkn](https://github.com/redhat-chaos/krkn) and needs a corresponding container in krkn-hub.

## What was scaffolded

Files added under \`${SCENARIO_NAME}/\`:
- \`Dockerfile.template\` — base image wiring; update title/description labels
- \`env.sh\` — environment variable defaults (TODO: fill in)
- \`run.sh\` — scenario entrypoint (TODO: fill in run logic)
- \`krknctl-input.json\` — input field definitions (TODO: fill in)

Other changes:
- \`docker-compose.yaml\` — new service entry added
- \`build.sh\` — added to SCENARIOS array

## Required follow-up

- [ ] Fill in \`${SCENARIO_NAME}/env.sh\` with scenario-specific environment variables
- [ ] Fill in \`${SCENARIO_NAME}/run.sh\` with the scenario run logic
- [ ] Fill in \`${SCENARIO_NAME}/krknctl-input.json\` with input field definitions
- [ ] Update \`Dockerfile.template\` title and description labels
- [ ] Add any scenario YAML templates needed
- [ ] Update documentation

Triggered by commit: ${COMMIT_SHA}"

  gh pr create \
    --repo redhat-chaos/krkn-hub \
    --title "Add container support for new scenario plugin: ${SCENARIO_NAME}" \
    --body "$PR_BODY" \
    --head "$BRANCH" \
    --base main
done
