kraken:
  distribution: openshift
  kubeconfig_path: $test_kube_config_path
  exit_on_failure: false
  litmus_version: v1.13.6
  litmus_uninstall: false
  chaos_scenarios:
    - $scenario_type:
        - $scenario_file $post_config
cerberus:
  cerberus_enabled: false
  cerberus_url: null
performance_monitoring:
  deploy_dashboards: false
  repo: https://github.com/cloud-bulldozer/performance-dashboards.git
  kube_burner_binary_url: https://github.com/cloud-bulldozer/kube-burner/releases/download/v0.9.1/kube-burner-0.9.1-Linux-x86_64.tar.gz
  capture_metrics: false
  config_path: config/kube_burner.yaml
  metrics_profile_path: config/metrics-aggregated.yaml
  prometheus_url: null
  prometheus_bearer_token: null
  uuid: null
  enable_alerts: false
  alert_profile: config/alerts
tunings:
  wait_duration: 6
  iterations: 1
  daemon_mode: false
