kraken:
    kubeconfig_path: /Users/prubenda/.kube/config #/root/.kube/config                    # Path to kubeconfig
    scenarios:  []                                           # List of policies/chaos scenarios to load
        #-    scenarios/etcd.yml
        #-    scenarios/openshift-kube-apiserver.yml
        #-    scenarios/openshift-apiserver.yml
        #-    scenarios/regex_openshift_pod_kill.yml
    network_scenarios:
        #-     scenarios/network_bandwidth.yaml
        -     scenarios/network_packet_loss.yaml
cerberus:
    cerberus_enabled: False                                # Enable it when cerberus is previously installed
    cerberus_url:                                          # When cerberus_enabled is set to True, provide the url where cerberus publishes go/no-go signal

tunings:
    wait_duration: 20                                      # Duration to wait between each chaos scenario
    iterations: 1                                          # Number of times to execute the scenarios
    daemon_mode: False                                     # Iterations are set to infinity which means that the cerberus will monitor the resources forever
