FROM quay.io/krkn-chaos/krkn:latest

ENV KUBECONFIG /home/krkn/.kube/config

COPY __SCENARIO__/env.sh /home/krkn/env.sh
COPY env.sh /home/krkn/main_env.sh
COPY __SCENARIO__/run.sh /home/krkn/run.sh
COPY common_run.sh /home/krkn/common_run.sh

LABEL krknctl.kubeconfig_path="/home/krkn/.kube/config"
LABEL krknctl.title="TODO: Scenario Title"
LABEL krknctl.description="TODO: Describe what this scenario does"

LABEL krknctl.input_fields='$KRKNCTL_INPUT'

ENTRYPOINT /home/krkn/kraken/containers/setup-ssh.sh && /home/krkn/run.sh
